apiVersion: v1
kind: Service
metadata:
  name: k8s-doc-example
  labels:
    app: k8s-doc-example
spec:
  selector:
    app: k8s-doc-example
  ports:
    - protocol: "TCP"
      port: 8088 # where service is running
      targetPort: 8088 # port exposed by the service
  type: NodePort # type of service
  